Registration login
Fstv-Electro/TaskPro-prj-9 pull request #14
Opened 2023-06-24 20:53 UTC by Mamont257

Зробив реєстрацію і вхід і повязав з бекендом

2023-06-25 07:18 UTC, Fstv-Electro requested changes
Компоненти в папці Components, для зручності можешь створити там папку Auth і туди все закинути.

2023-06-25 07:18 UTC, Fstv-Electro commented on src/redux/store.js
файл стор тільки 1 і тільки. Він знаходиться в redux.!!!!!

2023-06-25 07:18 UTC, Fstv-Electro commented on src/views/LoginView/LiginView.js
змінити назву фалу на LoginView

2023-06-25 07:18 UTC, Fstv-Electro commented on src/views/RegistrationView/RegistrationView.js
> +              />
А де кнопка ока, яке показує пароль?

2023-06-25 07:18 UTC, Fstv-Electro commented on src/views/welcomePage/welcomePage.js
![image](https://github.com/Fstv-Electro/TaskPro-prj-9/assets/104622826/331b100a-a1d7-4f03-8f0c-440630f3171f)
не грузить лого

2023-06-25 11:24 UTC, Mamont257 commented on src/views/welcomePage/welcomePage.js
Вже грузить

2023-06-25 11:24 UTC, Mamont257 commented on src/views/RegistrationView/RegistrationView.js
> +              />
Додав

2023-06-25 11:24 UTC, Mamont257 commented on src/views/LoginView/LiginView.js
Є

2023-06-25 11:24 UTC, Mamont257 commented on src/redux/store.js
Так і було, я тут нічого не міняв

2023-06-25 11:34 UTC, Mamont257 commented
Все поправив, ще пізніше додам валідацію форми

2023-06-25 11:37 UTC, Fstv-Electro commented on src/views/RegistrationView/RegistrationView.js
> +              />
ти шось наплутав
коли вводиш пароль він показує ****, а коли хочеш подивитись, що написав, потрібно щоб він показав прихований текст

2023-06-25 11:39 UTC, Fstv-Electro requested changes
Не правильно працює функціонал показати прихованний введений пароль

2023-06-25 11:40 UTC, Mamont257 commented on src/views/RegistrationView/RegistrationView.js
> +              />
Я ще його не реалізовував, поки тільки додав іконку

2023-06-26 06:59 UTC, Fstv-Electro approved these changes

2023-06-26 07:02 UTC, merged